:Author: Erik Homburg 2017

:License: Public Domain

= Project: Color Clock based on RGBDigits

A clock with 4 or 6 RGBDigits (7 segment displays with NeoPixel LED's,
www.rgbdigit.com). Uses my RGBDigitV2 class (github erikho/RGBDigitV2) as
interface to the hardware. The clock is controlled with a rotary encoder
with pushbutton function.
The software is tested with 4 digits on an Arduino Uno. It is suggested
to use an Arduino Nano V3 in order to get a compact realization.

normal mode:
rotate left/right: adjust display intensity
short press on the button: enter time set mode
time set mode:
rotate left/right with button not pressed: change digit position to change
rotate left/right with button pressed: change digit value
short press of button: set new time and leave edit mode
after 2 minutes without user action edit mode is left without change of time

The layout suggest the use of an Arduino Nano. Power supply through the USB
connector.

Please check the actual I2C connector pins for your particular Arduino.  

== Step 1: Installation
use either the Arduino Create web editor the Arduino IDE

== Step 2: Assemble the circuit
Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code
Arduino Create web editor: just upload colorClockWithSwitch.ino to your
Arduino
Arduino IDE: also install the required libraries as mentioned in
colorClockWithSwitch.ino

=== Folder structure

....
 colorClockWithSwitch                => Arduino sketch folder
  ├── colorClockWithSwitch.ino       => main Arduino file
  ├── schematics.png                 => required schematics
  ├── layout.png                     => the layout
  └── ReadMe.adoc                    => this file
....

=== License
This sofware is free software

=== BOM

|===
| ID | Part name         | Part number                    | Quantity  
| R1 | rotary encoder    | adafruit PEC11-4215F-S24 or eqv| 1  
| A1 | Arduino Nano V3   | A000005                        | 1  
| Z1 | Real Time Clock   | DS3231   ZS - 042              | 1  
| C1 | 100 muF Cap       |                                | 1
|===
